server.port=1090
spring.application.name=ecommerce-backend

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom_kashima
spring.datasource.username=postgres
spring.datasource.password=hiren12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings for PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Shows SQL queries in console easy debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


